In [4]:
lst =[]

for i in range (0,4):
    a =int(input())
    lst.append(a)
print(lst)

1
2
3
4
[1, 2, 3, 4]


In [6]:
import numpy as np
x=[1,2,3,4]
b=np.array(x)
print(b)


[1 2 3 4]


In [15]:
var1 = np.array([[1,2,7,4],[1,2,3,4]])
var2 = np.array([[2,3,4,5],[2,3,4,5]])

var3 = np.divide(var1,var2)
print(var3)
%timeit var3

[[0.5        0.66666667 1.75       0.8       ]
 [0.5        0.66666667 0.75       0.8       ]]
8.78 ns ± 0.0484 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [27]:
import numpy as np
var1 = np.array([[1,2,7,4],[1,2,3,4]])
var2=var1.copy()
print(var2)

var3=np.arange()
print(var3)


[[1 2 7 4]
 [1 2 3 4]]
[0 1 2]


In [48]:
import numpy as np
var1=np.array([[[1,2],[2,3]]])
var2=np.array([[[5,6],[7,8]]])

var3=np.stack(((var1,var2)),axis=1)

print(var3)

[[[[1 2]
   [2 3]]

  [[5 6]
   [7 8]]]]


In [56]:
import numpy as np
var1=np.array([[[1,2],[2,3]]])
var2=np.array([[[5,6],[7,8]]])

var3=np.stack(((var1,var2)),axis=1)

var4=np.array_split(var3,3,axis=1)
print(var4)

[array([[[[1, 2],
         [2, 3]]]]), array([[[[5, 6],
         [7, 8]]]]), array([], shape=(1, 0, 2, 2), dtype=int64)]


In [86]:
import numpy as np

var =np.array([1,2,3,4])

var2=var.reshape(1,4)
print(var2)

[[1 2 3 4]]


In [88]:
from PIL import Image
import numpy as np


pixels = [
   [(54, 54, 54), (232, 23, 93), (71, 71, 71), (168, 167, 167)],
   [(204, 82, 122), (54, 54, 54), (168, 167, 167), (232, 23, 93)],
   [(71, 71, 71), (168, 167, 167), (54, 54, 54), (204, 82, 122)],
   [(168, 167, 167), (204, 82, 122), (232, 23, 93), (54, 54, 54)]
]

# Convert the pixels into an array using numpy
array = np.array(pixels, dtype=np.uint8)

# Use PIL to create an image from the new array of pixels
new_image = Image.fromarray(array)
new_image.save('new.png')